Fixes custom config npm tut
comunica/website pull request #49
Opened 2024-08-13 09:40 UTC by mvanbrab

What I needed to do to make this tutorial work to "expose my custom config as an npm package".

2024-08-13 10:37 UTC, rubensworks requested changes
Thanks @mvanbrab! Just one suggestion.

2024-08-13 10:37 UTC, rubensworks commented on pages/docs/2_modify/1_getting_started/3_custom_init.md
> -    "postinstall": "npm run build"
"postinstall" is wrong indeed, but we'll probably want to replace it by "prepare".

2024-08-13 16:09 UTC, mvanbrab commented
If we add it as "prepare" script, we probably should remove the "prepublishOnly" script, also equal to "npm run build". See also <https://docs.npmjs.com/cli/v10/using-npm/scripts>

From: Ruben Taelman ***@***.***>
Sent: Tuesday, August 13, 2024 12:37 PM
To: comunica/website ***@***.***>
Cc: Martin Vanbrabant (UGent-imec) ***@***.***>; Mention ***@***.***>
Subject: Re: [comunica/website] Fixes custom config npm tut (PR #49)


@rubensworks requested changes on this pull request.

Thanks @mvanbrab<https://github.com/mvanbrab>! Just one suggestion.

________________________________

In pages/docs/2_modify/1_getting_started/3_custom_init.md<https://github.com/comunica/website/pull/49#discussion_r1715069763>:

> @@ -138,17 +135,21 @@ For this, add the following **scripts to our `package.json`** file:

     "prepublishOnly": "npm run build",

     "build:engine": "comunica-compile-config config/config-default.json > engine-default.js",

     "build:lib": "tsc",

-    "build": "npm run build:lib && npm run build:engine",

-    "postinstall": "npm run build"

"postinstall" is wrong indeed, but we'll probably want to replace it by "prepare".

-
Reply to this email directly, view it on GitHub<https://github.com/comunica/website/pull/49#pullrequestreview-2235187667>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABRGI5LVUE5JCL4NRDY4AVDZRHOWHAVCNFSM6AAAAABMN4JOJGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZVGE4DONRWG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-08-14 06:01 UTC, rubensworks commented
> If we add it as "prepare" script, we probably should remove the "prepublishOnly" script, also equal to "npm run build".

Yes, good idea!

2024-08-19 06:28 UTC, mvanbrab commented
Added "prepare" script, removed "prepublishOnly".

2024-08-19 11:19 UTC, merged

2024-08-19 11:19 UTC, rubensworks commented
Thanks @mvanbrab!